name: Makefile CI

on:
  push:
    branches: [ main, formesse ]
  pull_request:
    branches: [ main, formesse ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      working-directory: ./ft
      run: export TOOLCHAIN_BIN_PATH=./../gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf/bin
      
    - name: configure2
      run: export TOOLCHAIN_BIN_PATH=./gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf/bin
      
    - name: configure3
      run: ls
      
    - name: Make Project
      working-directory: ./ft
      run: make
      
    - name: Run check
      working-directory: ./t
      run: make check
      
    - name: Run distcheck
      working-directory: ./ft
      run: make distcheck
