name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      working-directory: ./ft
      run: ls
      
    - name: Install dependencies
      working-directory: ./ft
      run: make
      
    - name: Run check
      working-directory: ./t
      run: make check
      
    - name: Run distcheck
      working-directory: ./ft
      run: make distcheck
